#!/usr/bin/env python

from baremail import run_server

if __name__ == '__main__':
    try:
        cfile_name = sys.argv[1]
    except:
        print('Error: missing configuration file name')
        print('Usage: {} <config_file>'.format(sys.argv[0]))
        sys.exit(1)
    try:
        cfile = open(cfile_name, 'r')
        cfgdict = json.load(cfile)
    except Exception, msg:
        print('Configuration file error - {}'.format(msg))
    else:
        sys.exit(run_server(cfgdict))
